
    create table goods (
        price numeric(38,2),
        stock integer,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        name varchar(255),
        primary key (id)
    );

    create table orders (
        amount integer,
        created_at timestamp(6) not null,
        good_id bigint,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint,
        address varchar(255),
        primary key (id)
    );

    create table seckill_orders (
        amount integer,
        created_at timestamp(6) not null,
        good_id bigint,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint,
        primary key (id),
        unique (user_id, good_id)
    );

    create table users (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        email varchar(255),
        password varchar(255),
        username varchar(255),
        primary key (id)
    );

    alter table if exists orders 
       add constraint FKydga3l6xs2xuj0x0qik5ljje 
       foreign key (good_id) 
       references goods;

    alter table if exists orders 
       add constraint FK32ql8ubntj5uh44ph9659tiih 
       foreign key (user_id) 
       references users;

    alter table if exists seckill_orders 
       add constraint FKl83c4odo93f4l8bo0vwjy42s3 
       foreign key (good_id) 
       references goods;

    alter table if exists seckill_orders 
       add constraint FKarujr7hsyacg8166is3viisqv 
       foreign key (user_id) 
       references users;
